# Generated by Django 5.0.2 on 2024-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_poll_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
